# Generated by Django 5.2.8 on 2026-04-07 07:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('icon', models.CharField(default='fas fa-folder', max_length=50, verbose_name='图标')),
                ('color', models.CharField(default='#6c757d', help_text='HEX颜色代码，如：#FF6B6B', max_length=7, verbose_name='颜色')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '链接分类',
                'verbose_name_plural': '链接分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='描述')),
                ('icon', models.CharField(default='fas fa-link', max_length=50, verbose_name='图标')),
                ('is_new_tab', models.BooleanField(default=True, verbose_name='在新标签页打开')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='toolbox.linkcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '自定义链接',
                'verbose_name_plural': '自定义链接',
                'ordering': ['order', 'id'],
            },
        ),
    ]
