# Generated by Django 5.2.8 on 2025-11-25 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseworkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('color', models.CharField(default='#007bff', help_text='十六进制颜色代码', max_length=7, verbose_name='显示颜色')),
                ('icon', models.CharField(default='🏠', help_text='用emoji表示', max_length=2, verbose_name='图标')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '家务分类',
                'verbose_name_plural': '家务分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseworkTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='模板标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('default_duration', models.PositiveIntegerField(default=30, verbose_name='默认预计耗时(分钟)')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级')),
                ('frequency', models.CharField(choices=[('once', '一次性'), ('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='weekly', max_length=10, verbose_name='重复频率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housework.houseworkcategory', verbose_name='分类')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '家务模板',
                'verbose_name_plural': '家务模板',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Housework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='家务标题')),
                ('description', models.TextField(blank=True, verbose_name='详细描述')),
                ('planned_date', models.DateField(verbose_name='计划执行日期')),
                ('planned_duration', models.PositiveIntegerField(default=30, help_text='单位：分钟', verbose_name='预计耗时(分钟)')),
                ('actual_duration', models.PositiveIntegerField(blank=True, help_text='单位：分钟', null=True, verbose_name='实际耗时(分钟)')),
                ('frequency', models.CharField(choices=[('once', '一次性'), ('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='once', max_length=10, verbose_name='重复频率')),
                ('status', models.CharField(choices=[('pending', '待完成'), ('in_progress', '进行中'), ('completed', '已完成'), ('skipped', '已跳过')], default='pending', max_length=20, verbose_name='状态')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '紧急')], default=2, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='housework.houseworkcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '家务记录',
                'verbose_name_plural': '家务记录',
                'ordering': ['planned_date', '-priority', 'created_at'],
                'indexes': [models.Index(fields=['user', 'planned_date'], name='housework_h_user_id_bb02f0_idx'), models.Index(fields=['status', 'planned_date'], name='housework_h_status_e312ee_idx'), models.Index(fields=['category', 'planned_date'], name='housework_h_categor_cfd17c_idx')],
            },
        ),
    ]
