# Generated by Django 5.2.8 on 2025-11-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housework',
            name='weekdays',
            field=models.JSONField(blank=True, default=list, help_text='每周重复的星期几（JSON格式）', verbose_name='重复星期'),
        ),
    ]
