# Generated by Django 5.2.8 on 2025-12-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        ('housework', '0002_housework_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='housework',
            name='family',
            field=models.ForeignKey(blank=True, help_text='选择关联的家庭组', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='houseworks', to='family.family', verbose_name='家庭'),
        ),
    ]
