# Generated by Django 5.2.8 on 2025-12-08 02:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='家庭名称')),
                ('description', models.TextField(blank=True, help_text='描述一下您的家庭特色', verbose_name='家庭描述')),
                ('invite_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='邀请码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('max_members', models.PositiveIntegerField(default=10, help_text='家庭组最大成员数量', verbose_name='最大成员数')),
                ('is_public', models.BooleanField(default=False, help_text='是否允许搜索到本家庭组', verbose_name='公开家庭组')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='family_avatars/', verbose_name='家庭头像')),
                ('color_theme', models.CharField(default='#a8edea', help_text='十六进制颜色代码', max_length=7, verbose_name='主题色')),
            ],
            options={
                'verbose_name': '家庭组',
                'verbose_name_plural': '家庭组',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=200, verbose_name='个人简介')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='启用通知')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='邮件通知')),
                ('current_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='family.family', verbose_name='当前家庭')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='family_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '家庭主'), ('admin', '管理员'), ('member', '成员')], default='member', max_length=10, verbose_name='角色')),
                ('nickname', models.CharField(blank=True, help_text='在家庭中的显示名称', max_length=50, verbose_name='家庭昵称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='最后活跃')),
                ('can_create_events', models.BooleanField(default=True, verbose_name='可创建事件')),
                ('can_create_housework', models.BooleanField(default=True, verbose_name='可创建家务')),
                ('can_invite_members', models.BooleanField(default=False, verbose_name='可邀请成员')),
                ('can_manage_family', models.BooleanField(default=False, verbose_name='可管理家庭')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='family.family', verbose_name='家庭')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '家庭成员',
                'verbose_name_plural': '家庭成员',
                'ordering': ['-joined_at'],
                'indexes': [models.Index(fields=['user', 'family'], name='family_fami_user_id_2cd90a_idx'), models.Index(fields=['family', 'role'], name='family_fami_family__8d5aff_idx')],
                'unique_together': {('user', 'family')},
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已接受'), ('rejected', '已拒绝'), ('expired', '已过期')], default='pending', max_length=10, verbose_name='状态')),
                ('message', models.TextField(blank=True, help_text='对被邀请人的留言', verbose_name='邀请消息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='邀请时间')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='family.family', verbose_name='家庭')),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='被邀请人')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='邀请人')),
            ],
            options={
                'verbose_name': '邀请',
                'verbose_name_plural': '邀请',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invitee', 'status'], name='family_invi_invitee_05f084_idx'), models.Index(fields=['family', 'status'], name='family_invi_family__64a204_idx')],
                'unique_together': {('family', 'invitee')},
            },
        ),
    ]
