# Generated by Django 5.2.8 on 2025-12-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
    ]

    operations = [
    ]
