# Generated by Django 5.2.8 on 2025-11-21 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="事件名称")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="可选的详细描述", verbose_name="描述"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("one_time", "一次性提醒"),
                            ("annual", "每年重复（纪念日/节日）"),
                            ("reminder", "提醒（可作为一次性或重复）"),
                            ("monthly_weekend", "每月第N个周末"),
                        ],
                        default="one_time",
                        help_text="选择事件的重复类型",
                        max_length=32,
                        verbose_name="事件类型",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="适用于一次性、年度和提醒类型的事件",
                        null=True,
                        verbose_name="日期",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        blank=True, help_text="可选的具体时间", null=True, verbose_name="时间"
                    ),
                ),
                (
                    "week_order",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "第1个周末"),
                            (2, "第2个周末"),
                            (3, "第3个周末"),
                            (4, "第4个周末"),
                        ],
                        help_text="适用于每月第N个周末类型的事件",
                        null=True,
                        verbose_name="周末顺序",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, help_text="是否启用此事件", verbose_name="启用"
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="数值越大优先级越高，用于排序", verbose_name="优先级"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "事件",
                "verbose_name_plural": "事件",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
