# Generated by Django 5.2.8 on 2025-11-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '周一'), (1, '周二'), (2, '周三'), (3, '周四'), (4, '周五'), (5, '周六'), (6, '周日')], help_text='适用于每周重复类型的事件，选择周几重复', null=True, verbose_name='星期几'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('one_time', '一次性提醒'), ('annual', '每年重复（纪念日/节日）'), ('reminder', '提醒（可作为一次性或重复）'), ('monthly_weekend', '每月第N个周末'), ('weekly', '每周重复')], default='one_time', help_text='选择事件的重复类型', max_length=32, verbose_name='事件类型'),
        ),
    ]
