# Generated by Django 5.2.8 on 2025-12-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_weekday_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('one_time', '一次性提醒'), ('annual', '每年重复（纪念日/节日）'), ('reminder', '提醒（可作为一次性或重复）'), ('monthly_weekend', '每月第N个周末')], default='one_time', help_text='选择事件的重复类型', max_length=32, verbose_name='事件类型'),
        ),
    ]
