# Generated by Django 5.2.8 on 2025-12-08 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_weekday_alter_event_event_type'),
        ('family', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='family',
            field=models.ForeignKey(blank=True, help_text='选择关联的家庭组，留空则仅个人可见', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='family.family', verbose_name='家庭'),
        ),
    ]
